
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

mqtt: 
  certificate: ca.crt
  tls_insecure: true

sensor:
  - platform: mqtt
    name: Moisture value
    state_topic: "abegghome/moisture/state"
    unit_of_measurement: "%"
    value_template: "{{ value_json.value | round(1) }}"
    qos: 1
    unique_id: sensor.moisture_value
  - platform: mqtt
    name: Moisture Raw value
    state_topic: "abegghome/moisture/debug"
    value_template: "{{ value_json.value }}"
    qos: 1
    unique_id: sensor.moisture_value_raw
binary_sensor:
  - platform: mqtt
    name: Pump
    state_topic: "abegghome/pump/state"
    payload_on: "on"
    payload_off: "off"
    availability:
      topic: "abegghome/pump/availability"
      payload_available: "on"
      payload_not_available: "off"
    expire_after: 60
    qos: 1
    unique_id: sensor.pump

input_number:
  air_value:
    name: Air Value
    initial: 3.3
    min: 0
    max: 3.3
    step: 0.1
    icon: mdi:air-filter
    mode: box
    unit_of_measurement: "volts"
  water_value:
    name: Water Value
    initial: 0
    min: 0
    max: 3.3
    step: 0.1
    icon: mdi:waves
    mode: box
    unit_of_measurement: "volts"
  pump_runtime:
    name: Pump Runtime
    initial: 5
    min: 0
    max: 60
    step: 1
    unit_of_measurement: "seconds"
    icon: mdi:water-pump
    mode: box
  moisture_sampling_time:
    name: Moisture Sampling Time
    initial: 300
    min: 10
    max: 3600
    step: 10
    unit_of_measurement: "seconds"
    icon: mdi:water-sync
    mode: box
  watering_time:
    name: Watering Time
    initial: 1
    min: 1
    max: 24
    step: 1
    unit_of_measurement: "hours"
    icon: mdi:water-check
    mode: box
  moisture_tresh:
    name: Moisture Treshold
    initial: 50
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    icon: mdi:water-percent-alert
    mode: slider

input_boolean:
  switch_pump:
    name: Pump switch
    initial: on
    icon: mdi:pump
  pump_override:
    name: Pump override
    initial: off
    icon: mdi:radiobox-marked

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 108.162.192.0/18
    - 131.0.72.0/22
    - 141.101.64.0/18
    - 162.158.0.0/15
    - 172.64.0.0/13
    - 173.245.48.0/20
    - 188.114.96.0/20
    - 190.93.240.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 127.0.0.1
    - ::1

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
